---
title: "HFPG"
output: html_document
date: "`r Sys.Date()`"
---

```{r include=FALSE}
# -----------------------------------------
# Carrega pacotes
# -----------------------------------------

library(ggplot2)
library(ggthemes)
library(plotly)
library(tidyverse)
library(readr)
library(here)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)
library(hrbrthemes)
library(shadowtext)

# -----------------------------------------
# Carrega arquivos de dados
# -----------------------------------------

#From GBD tools
GBD_3 <-
  readr::read_csv(file = here::here("GBD-dados", "GBD_3.csv"))
GBD_4 <-
  readr::read_csv(file = here::here("GBD-dados", "GBD_4.csv"))
SEV <- readr::read_csv(file = here::here("GBD-dados", "SEV.csv"))

#Rate of changes
SEV_ROC <-
  readr::read_csv(file = here::here("GBD-dados", "SEV_ROC.csv"))
GBD_ROC <-
  readr::read_csv(file = here::here("GBD-dados", "GBD_ROC.csv"))

#From GHDx
SDI <-
  readr::read_csv(file = here::here("GBD-dados", "GBD_SDI_1990_TO_2019.csv"))
GBD_POP_1990 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1990_Y2020M10D15.CSV"))
GBD_POP_1991 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1991_Y2020M10D15.CSV"))
GBD_POP_1992 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1992_Y2020M10D15.CSV"))
GBD_POP_1993 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1993_Y2020M10D15.CSV"))
GBD_POP_1994 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1994_Y2020M10D15.CSV"))
GBD_POP_1995 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1995_Y2020M10D15.CSV"))
GBD_POP_1996 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1996_Y2020M10D15.CSV"))
GBD_POP_1997 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1997_Y2020M10D15.CSV"))
GBD_POP_1998 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1998_Y2020M10D15.CSV"))
GBD_POP_1999 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_1999_Y2020M10D15.CSV"))
GBD_POP_2000 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2000_Y2020M10D15.CSV"))
GBD_POP_2001 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2001_Y2020M10D15.CSV"))
GBD_POP_2002 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2002_Y2020M10D15.CSV"))
GBD_POP_2003 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2003_Y2020M10D15.CSV"))
GBD_POP_2004 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2004_Y2020M10D15.CSV"))
GBD_POP_2005 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2005_Y2020M10D15.CSV"))
GBD_POP_2006 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2006_Y2020M10D15.CSV"))
GBD_POP_2007 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2007_Y2020M10D15.CSV"))
GBD_POP_2008 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2008_Y2020M10D15.CSV"))
GBD_POP_2009 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2009_Y2020M10D15.CSV"))
GBD_POP_2010 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2010_Y2020M10D15.CSV"))
GBD_POP_2011 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2011_Y2020M10D15.CSV"))
GBD_POP_2012 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2012_Y2020M10D15.CSV"))
GBD_POP_2013 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2013_Y2020M10D15.CSV"))
GBD_POP_2014 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2014_Y2020M10D15.CSV"))
GBD_POP_2015 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2015_Y2020M10D15.CSV"))
GBD_POP_2016 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2016_Y2020M10D15.CSV"))
GBD_POP_2017 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2017_Y2020M10D15.CSV"))
GBD_POP_2018 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2018_Y2020M10D15.CSV"))
GBD_POP_2019 <-
  read_csv(file = here::here("GBD-dados", "IHME_GBD_2019_POP_2019_Y2020M10D15.CSV"))

# -----------------------------------------
# Combina e formata objetos de dados
# -----------------------------------------

GBD <- GBD_3 %>%
  bind_rows(GBD_4) %>%
  bind_rows(SEV) %>%
  mutate_at(c('cause'), ~replace_na(.,"All causes"))

rm(GBD_3, GBD_4, SEV) #Dont waste my precious RAM


GBD <- GBD %>%
  mutate(age = recode(age, "80-84" = "80-84 years",
                      "85-89" = "85-89 years",
                      "90-94" = "90-94 years"),
         year = as.factor(year))%>%
  mutate(age = as.factor(age)) %>%
  mutate(measure = recode(measure,
                          "YLDs (Years Lived with Disability)" = "YLDs",
                          "YLLs (Years of Life Lost)" = "YLLs",
                          "DALYs (Disability-Adjusted Life Years)" = "DALYs",
                          "Summary exposure value" = "SEV"),
         location = recode(location,
                           "Bolivia (Plurinational State of)" = "Bolivia",
                           "Venezuela (Bolivarian Republic of)" = "Venezuela"),
         val_cat = cut(x = GBD$val,
                       breaks = c(-Inf, 1, 10, 100, 500,
                                  1000, 2500, 5000, Inf),
                       labels = c("0 - 1",
                                  "1 - 10",
                                  "10 - 100",
                                  "100 - 500",
                                  "500 - 1000",
                                  "1000 - 2500",
                                  "2500 - 5000",
                                  ">5000")))%>% 
  mutate(age = recode(age,  "<5 years"="<5",
                            "5-9 years"="5-9",
                            "10-14 years"="10-14",
                            "15-19 years"="15-19",
                            "20-24 years"="20-24",
                            "25-29 years"="25-29",
                            "30-34 years"="30-34",
                            "35-39 years"="35-39",
                            "40-44 years"="40-44",
                            "45-49 years"="45-49",
                            "50-54 years"="50-54",
                            "55-59 years"="55-59",
                            "60-64 years"="60-64",
                            "65-69 years"="65-69",
                            "70-74 years"="70-74",
                            "75-79 years"="75-79",
                            "80-84 years"="80-84",
                            "85-89 years"="85-89",
                            "90-94 years"="90-94",
                            "95+ years"="95+")) %>% 
  mutate(age = factor(age, levels = c("<5",
                                      "5-9",
                                      "10-14",
                                      "15-19",
                                      "20-24",
                                      "25-29",
                                      "30-34",
                                      "35-39",
                                      "40-44",
                                      "45-49",
                                      "50-54",
                                      "55-59",
                                      "60-64",
                                      "65-69",
                                      "70-74",
                                      "75-79",
                                      "80-84",
                                      "85-89",
                                      "90-94",
                                      "95+",
                                      "All ages",
                                      "Age-standardized")))%>% 
  mutate(measure = factor(measure, levels = c("DALYs",
                                              "YLDs",
                                              "YLLs",
                                              "Deaths",
                                              "SEV")))


GBD_POP <- GBD_POP_1990 %>% 
  bind_rows(GBD_POP_1991,
            GBD_POP_1992,
            GBD_POP_1993,
            GBD_POP_1994,
            GBD_POP_1995,
            GBD_POP_1996,
            GBD_POP_1997,
            GBD_POP_1998,
            GBD_POP_1999,
            GBD_POP_2000,
            GBD_POP_2001,
            GBD_POP_2002,
            GBD_POP_2003,
            GBD_POP_2004,
            GBD_POP_2005,
            GBD_POP_2006,
            GBD_POP_2007,
            GBD_POP_2008,
            GBD_POP_2009,
            GBD_POP_2010,
            GBD_POP_2011,
            GBD_POP_2012,
            GBD_POP_2013,
            GBD_POP_2014,
            GBD_POP_2015,
            GBD_POP_2016,
            GBD_POP_2017,
            GBD_POP_2018,
            GBD_POP_2019) %>% 
  rename(location = location_name,
         sex = sex_name,
         age = age_group_name,
         year = year_id,
         pop = val) %>%
  select(location, sex, age, year, pop) %>%
  mutate(location = recode(location,
                           "Bolivia (Plurinational State of)" = "Bolivia",
                           "Venezuela (Bolivarian Republic of)" = "Venezuela"),
         sex = recode(sex,
                      "both" = "Both",
                      "male" = "Male",
                      "female" = "Female"),
         age = as.factor(age),
         year = as.factor(year))%>%
  filter(location %in% c("Argentina",
                         "Bolivia",
                         "Brazil",
                         "Chile",
                         "Colombia",
                         "Ecuador",
                         "Guyana",
                         "Paraguay",
                         "Peru",
                         "Suriname",
                         "Uruguay",
                         "Venezuela"),
         sex == "Both") %>%
  mutate(age = recode(age,  "Under 5"="<5",
                            "5 to 9"="5-9",
                            "10 to 14"="10-14",
                            "15 to 19"="15-19",
                            "20 to 24"="20-24",
                            "25 to 29"="25-29",
                            "30 to 34"="30-34",
                            "35 to 39"="35-39",
                            "40 to 44"="40-44",
                            "45 to 49"="45-49",
                            "50 to 54"="50-54",
                            "55 to 59"="55-59",
                            "60 to 64"="60-64",
                            "65 to 69"="65-69",
                            "70 to 74"="70-74",
                            "75 to 79"="75-79",
                            "80 to 84"="80-84",
                            "85 to 89"="85-89",
                            "90 to 94"="90-94",
                            "95 plus"="95+",
                      "All Ages" = "All ages")) %>%
  filter(age %in% c("<5",
                    "5-9",
                    "10-14",
                    "15-19",
                    "20-24",
                    "25-29",
                    "30-34",
                    "35-39",
                    "40-44",
                    "45-49",
                    "50-54",
                    "55-59",
                    "60-64",
                    "65-69",
                    "70-74",
                    "75-79",
                    "80-84",
                    "85-89",
                    "90-94",
                    "95+",
                    "All ages")) %>% 
  mutate(age = factor(age, levels = c("<5",
                                      "5-9",
                                      "10-14",
                                      "15-19",
                                      "20-24",
                                      "25-29",
                                      "30-34",
                                      "35-39",
                                      "40-44",
                                      "45-49",
                                      "50-54",
                                      "55-59",
                                      "60-64",
                                      "65-69",
                                      "70-74",
                                      "75-79",
                                      "80-84",
                                      "85-89",
                                      "90-94",
                                      "95+",
                                      "All ages")))

rm(GBD_POP_1990,
   GBD_POP_1991,
   GBD_POP_1992,
   GBD_POP_1993,
   GBD_POP_1994,
   GBD_POP_1995,
   GBD_POP_1996,
   GBD_POP_1997,
   GBD_POP_1998,
   GBD_POP_1999,
   GBD_POP_2000,
   GBD_POP_2001,
   GBD_POP_2002,
   GBD_POP_2003,
   GBD_POP_2004,
   GBD_POP_2005,
   GBD_POP_2006,
   GBD_POP_2007,
   GBD_POP_2008,
   GBD_POP_2009,
   GBD_POP_2010,
   GBD_POP_2011,
   GBD_POP_2012,
   GBD_POP_2013,
   GBD_POP_2014,
   GBD_POP_2015,
   GBD_POP_2016,
   GBD_POP_2017,
   GBD_POP_2018,
   GBD_POP_2019) #Dont waste my precious RAM


SDI <- SDI %>% 
  filter(Location %in% c("Argentina",
                         "Bolivia",
                         "Brazil",
                         "Chile",
                         "Colombia",
                         "Ecuador",
                         "Guyana",
                         "Paraguay",
                         "Peru",
                         "Suriname",
                         "Uruguay",
                         "Venezuela"))

SDI_pivot <- SDI %>%
  pivot_longer(cols = c("1990",
                        "1991",
                        "1992",
                        "1993",
                        "1994",
                        "1995",
                        "1996",
                        "1997",
                        "1998",
                        "1999",
                        "2000",
                        "2001",
                        "2002",
                        "2003",
                        "2004",
                        "2005",
                        "2006",
                        "2007",
                        "2008",
                        "2009",
                        "2010",
                        "2011",
                        "2012",
                        "2013",
                        "2014",
                        "2015",
                        "2016",
                        "2017",
                        "2018",
                        "2019"),
               names_to = "year",
               values_to = "SDI")

SEV_ROC <- SEV_ROC %>% 
  mutate(cause = "All causes")

GBD_ROC_1990_to_2019 <- GBD_ROC %>%
  rbind(SEV_ROC) %>% 
  mutate(measure = recode(measure,
                          "YLDs (Years Lived with Disability)" = "YLDs",
                          "YLLs (Years of Life Lost)" = "YLLs",
                          "DALYs (Disability-Adjusted Life Years)" = "DALYs",
                          "Summary exposure value" = "SEV")) %>%
  mutate(location = recode(location,
                           "Bolivia (Plurinational State of)" = "Bolivia",
                           "Venezuela (Bolivarian Republic of)" = "Venezuela")) %>%
  mutate(year_end = as.factor(year_end)) %>%
  select(-c("rei", "year_start", "year_end")) %>%
  rename(ROC_val = val,
         ROC_upper = upper,
         ROC_lower = lower) %>% 
  mutate(measure = factor(measure, levels = c("DALYs",
                                              "YLDs",
                                              "YLLs",
                                              "Deaths",
                                              "SEV")))


rm(SEV_ROC, GBD_ROC)

SA_map <- ne_countries(scale = "medium",
                       type = "map_units",
                       returnclass = "sf") %>%
  filter(name %in% c("Argentina",
                     "Bolivia",
                     "Brazil",
                     "Chile",
                     "Colombia",
                     "Ecuador",
                     "Guyana",
                     "Paraguay",
                     "Peru",
                     "Suriname",
                     "Uruguay",
                     "Venezuela"))



GBD <- GBD %>%
  full_join(SDI_pivot, by = c("location" = "Location", "year" = "year")) %>%
  full_join(GBD_POP, by=c("location"="location",
                          "age"="age",
                          "sex"="sex",
                          "year"="year")) 

rm(SDI_pivot)

SA_SUM <- GBD %>%
  filter(metric == "Number",age != "Age-standardized") %>%
  group_by(measure,sex,age,cause,year) %>%
  summarise(number = sum(val), pop = sum(pop)) %>%
  mutate(rate = (number/pop)*100000)


SA_age_stand <- GBD %>% select(-c(pop)) %>% 
  filter(metric == "Rate",age == "Age-standardized", cause == "All causes") %>% 
  right_join(GBD_POP %>% filter(age == "All ages") %>% 
                        select(-c(sex, age)), 
            by=c("location"="location",
                          "year"="year")) %>% 
  group_by(measure, year) %>% 
  summarise(val = weighted.mean(val, pop))


```

```{r fig.width=10}
# -----------------------------------------
# Gráfico da América do Sul (dados demograficos)
# -----------------------------------------

df <- SA_SUM %>% 
      filter(measure == "DALYs",
             cause == "All causes") %>% 
      mutate(pop_mil = pop/1000000,
             year = as.numeric(year))

p <- ggplot(data = df %>% filter(age != "All ages"),
            mapping = aes(x = age, y = pop_mil,
                          color = year, group = year)) +
  geom_line() + geom_point() +
  scale_color_viridis_b(direction = -1, n.breaks = 29)+
  labs(color = "Measure", y = "Population (in millions)", x = "Year",
       title = "Age distribution between 1990-2019 in South America") +
  theme_bw() +
  coord_flip()+
  theme(legend.position = "right",
        legend.key.height = unit(2, "cm"),
        legend.text = element_text(size = 6))

p

#----------------------------------------
p <- ggplot(data = df %>% filter(age == "All ages"),
            mapping = aes(x = year, y = pop_mil,
                          fill = year)) +
      geom_col()+
      theme_bw() +
      coord_cartesian(ylim = c(200,500), xlim = c(1990,2019))+
      labs(color = "Year", y = "Population (in millions)", x = "Year",
           title = "Population in South America between 1990-2019") +
      scale_fill_viridis_c(direction = -1)
  
p

# -----------------------------------------
# Gráfico da América do Sul (Medidas em número)
# -----------------------------------------

df <- SA_SUM %>%
  filter(sex %in% "Both") %>%
  filter(age %in% "All ages") %>%
  filter(cause == "All causes") %>% 
  mutate(number_millions = number/1000000)

p <- ggplot(data = df,
            mapping = aes(x = year, y = number_millions,
                          color = measure, group = measure)) +
  geom_line() + geom_point() +
  scale_color_brewer(palette="Dark2") +
  labs(color = "Measure", y = "Number (in millions)", x = "Year",
       title = "Raw number of DALYs, YLDs, YLLs and deaths in South America since 1990") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1))

p


# -----------------------------------------
# Gráfico da América do Sul (Medidas em taxa)
# -----------------------------------------

p <- ggplot(data = df,
            mapping = aes(x = year, y = rate,
                          color = measure, group = measure)) +
  geom_line() + geom_point() +
  scale_color_brewer(palette="Dark2") +
  labs(#caption = "Rate of DALYs, YLDs, YLLs in South America",
    color = "Measure", y = "Rate (100,000)(All ages)", x = "Year",
    title = "Rate of DALYs, YLDs, YLLs and Deaths in South America without age-standardizing") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1))

p

# -----------------------------------------
# Gráfico da América do Sul (Medidas em taxa)
# AGE STANDARDIZED (Rate age-stand de cada pais com media ponderada pelas pop do ano)
# -----------------------------------------
df <- SA_age_stand


p <- ggplot(data = df,
            mapping = aes(x = year, y = val,
                          color = measure, group = measure)) +
  geom_line() + geom_point() +
  scale_color_brewer(palette="Dark2") +
  labs(#caption = "Rate of DALYs, YLDs, YLLs in South America",
    color = "Measure", y = "Rate (100,000)(Age standardized)", x = "Year",
    title = "Age-standardized rate of DALYs, YLDs, YLLs and Deaths in South America") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1))

p

# -----------------------------------------
# Gráfico da América do Sul por faixa etaria (Medidas em numeros)
# -----------------------------------------

df <- SA_SUM %>%
  filter(sex %in% "Both") %>%
  filter(age != "All ages") %>% 
  filter(cause == "All causes") %>%
  mutate(year = as.numeric(year),
         number_mil = number/1000000) #só assim fiz a escala ficar bonitinha

p <- ggplot(data = df,
            mapping = aes(x = age, y = number_mil,
                          color = year, group = year)) +
  geom_line() + geom_point() +
  labs(color = "Year", y = "number(in millions)", x = "Age group",
       title = "Number of DALYs, YLDs, YLLs and Deaths in South America by age groups since 1990") +
  theme_bw() +
  scale_color_viridis_b(direction = -1,
                        n.breaks = 29)+
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.key.height = unit(2, "cm"),
        legend.text = element_text(size = 6)) +
  facet_wrap( ~ measure,  scales = "free_y")
p

#falta conseguir colocar os extremos (1990-2019), mas já ta legal

# -----------------------------------------
# Gráfico da América do Sul por faixa etaria (Medidas em taxas)
# -----------------------------------------

df <- SA_SUM %>%
  filter(sex %in% "Both") %>%
  filter(age != "All ages") %>% 
  filter(cause == "All causes") %>% 
  mutate(year = as.numeric(year)) #só assim fiz a escala ficar bonitinha

p <- ggplot(data = df,
            mapping = aes(x = age, y = rate,
                          color = year, group = year)) +
  geom_line() + geom_point() +
  labs(color = "Year", y = "Rate (100,000)", x = "Age group",
       title = "Rate of DALYs, YLDs, YLLs and Deaths in South America by age groups since 1990") +
  theme_bw() +
  scale_color_viridis_b(direction = -1,
                        n.breaks = 29)+
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.key.height = unit(2, "cm"),
        legend.text = element_text(size = 6)) +
  facet_wrap( ~ measure,  scales = "free_y")
p

#falta conseguir colocar os extremos (1990-2019), mas já ta legal

# -----------------------------------------
# Gráfico da América do Sul (rate of change)
# -----------------------------------------


df <- GBD_ROC_1990_to_2019 %>% 
  filter(age == "Age-standardized") %>% 
  filter(cause == "All causes") %>% 
  filter(metric == "Rate")

p <- ggplot(data = df,
            mapping = aes(x = location,
                          y = ROC_val,
                          fill = measure)) +
  geom_bar(position = position_dodge(.9), stat = "identity") +
  geom_errorbar(aes(ymin = ROC_lower, ymax = ROC_upper),
                size = 0.5,
                width = 0.5,
                position = position_dodge(.9)) +
  labs(x = "Country", y = "Annualized Rate of Change (%) from 1990 to 2019",
       fill = "", caption = "Age-standardized",
       title = "Annualized Rate of Change (%) of DALYs, YLDs, YLLs, Deaths and SEV from 1990 to 2019 in South America countries") +
  theme_bw() +
  scale_fill_viridis_d()+
  theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1))

p

# -----------------------------------------
# Rate of measures each country from 1990 to 2019
# -----------------------------------------
df <- GBD %>%
  filter(age == "Age-standardized",
         cause == "All causes",
         metric == "Rate")

p <- ggplot() +
  geom_line(data = df, mapping = aes(x = year, y = val, color = measure, group = measure)) +
  facet_wrap( ~ location,  scales = "free_y") +
  labs(title = "Rate of DALYs, YLDs, YLLs, Deaths and SEV since 1990 in South America countries",
       x = "", y = "Rate(per 100.000", caption = "Age-standardized")+
  theme_bw() +
  theme(legend.position = "right", axis.text.x = element_text(angle = 45, hjust = 1))

p


# -----------------------------------------
# heatmap countries and causes in 2019
# -----------------------------------------

df <- GBD %>% 
  filter (metric =="Rate", 
          age == "Age-standardized",
          measure != "SEV",
          year == "2019")



p <- ggplot(df, mapping = aes(x = location, y = cause, fill = val_cat))+
  geom_tile(color = "white", lwd = 0)+
  
  geom_shadowtext(aes(label = round(val, digits = 1)), color = "white",
                  size = 2) +
  scale_fill_viridis_d(direction = -1)+
 # ggthemes::theme_base() +
  theme_bw()+
  facet_grid(~measure)+
  labs(title = "DALYs per 100.000 for each cause by country in 2019, both sexes", 
       fill = "DALYs per 100.000",
       x = "", y= "", caption = "Age-standardized")+
  theme(
    axis.text.x = element_text(hjust = 1,
                               angle = 45,
                               size = 8),
    plot.title = element_text(hjust = 0.5))


p


```
